### PR TITLE
Updated to 3.0.12.4

### PR DESCRIPTION
**Pull request by c3b-watzefak**
Signed-off-by: Eibo Richter <eibo.richter@c3b.info>

### CODE REVIEW

**Comment by c3b-watzefak** [comment]
Done. Check the other pull request

**Comment by SolidNerd** [comment]
It seems #4  is broken. I will merge this instead. Okay ?

**Comment by c3b-watzefak** [comment]
oh, I got confused. sorry. Just learning this...

**Comment by SolidNerd** [comment]
I don't know what was happing with #4.  But thanks for your effort again.

**Comment by SolidNerd** [comment]
@c3b-watzefak Probably i know why your #4 was broken. I guess the problem was that you reforked this repo so github could not find the master. To Update your fork you could do the following steps:

1. Add the original repo as a remote in this case it would `git remote add <NAME> git@github.com:SolidNerd/docker-teamspeak.git`. I would like to call it upstream so the command is `git remote add  upstream git@github.com:SolidNerd/docker-teamspeak.git`.

2. Update your remotes with `git fetch --all`. This will get all new changes but doesn't change your workdir.

3. Now you can Update your current branch(master) with a rebase `git rebase upstream/master`. This will update your fork with the changes from upstream repo.

If you have any other questions feel free to ask.

**Pull request merged**
